### ISSUE TITLE
asyncio.run() runtimeerror in uvicorn when running Shiny app

### ISSUE THREAD

**Issue by verweijs** [smc40/askyourdocs#5]
Hi all,

I am trying to play around with the git repos from the workshop, but do not manage to get the code of the Shiny app  working:
When running the `app.py` script, I get the following output, where `asyncio.run()` in `uvicorn` seems to lead to a `RuntimeError`

Did you experience the same problems? If so, how did you solve it?

```
ShinyDeprecationWarning: panel_main(width=)` is being ignored. Given the sidebar width, the main panel will take up the remaining horizontal space.
  ui.panel_main(
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/xx/my_app/app.py", line 112, in <module>
    run_app(host='127.0.0.1', port=8000, autoreload_port=0, reload=False,  # ws_max_size=16777216,
  File "/xx/venv/lib/python3.10/site-packages/shiny/_main.py", line 255, in run_app
    uvicorn.run(  # pyright: ignore[reportUnknownMemberType]
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/xx/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/usr/lib/python3.10/multiprocessing/process.py:330: RuntimeWarning: coroutine 'Server.serve' was never awaited
  traceback.print_exc()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by nicoapg** [comment]
I have run in a similar issue in the past. As far as I remember, this happens because you are running multiple processes at the same time.  You see this in this part of the error:

` asyncio.run() cannot be called from a running event loop
`

Why this happens can have multiple origins but in the end is that you have parallel loops taking place. If you have tried multiple time to run the script on different consoles, could already be a problem, if you have uncommented the code right at the bottom of the script and run it, it may also generate issues. Did it run once and then it broke down? or did you not get at all to run it?

Also, how are you running the app, step by step?

**Comment by verweijs** [comment]
**EDIT: never mind, the code at the bottom of `app.py` was indeed uncommented.**

It did not run at all. I followed different steps, all leading directly to the `RuntimeError` of `asycncio.run()`. 

First I ran the `app.py`  script in a Python console immediately leading to this `asyncio.run()` error. Then I alternatively ran the `app.py` script through the Ubuntu command terminal `python3 app.py` again leading to the same error. Same for running `shiny run --reload app.py` in the command terminal

What somehow at least led to the creation of the  "Hello Shiny" slider page is running
`shiny create my_app` in the root of the repository, creating:
```
root
app.py (as cloned from Github)
|-- my_app
    |-- app.py (slider page)
```
but not sure how to continue from there onwards
